filipek.pl/Models/Report.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace filipek.pl.Models
{
    public class Report
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public string Category { get; set; }
        public DateTime Data_of_issue { get; set; }
        public string Status { get; set; }
        public string ReplyReport { get; set; }
        public ApplicationUser User { get; set; }
    }
}

filipek.pl/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using filipek.pl.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace filipek.pl.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reports
        public ActionResult Index()
        {
            return View(db.Reports.ToList());
        }

        // GET: Reports/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // GET: Reports/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: Reports/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,Type,Category,Data_of_issue,Status")] Report report)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            ApplicationUser currentUser = UserManager.FindById(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                report.Data_of_issue = DateTime.Now;
                report.User = currentUser;
                db.Reports.Add(report);
                db.SaveChanges();
                ViewBag.Added = "Sukces";
                return RedirectToAction("Create");
            }
            
            return View( );
        }

        // GET: Reports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // POST: Reports/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,Type,Category,Data_of_issue,ReplyReport,Status")] Report report)
        {
            if (ModelState.IsValid)
            {
                report.Data_of_issue = DateTime.Now;
                db.Entry(report).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit");
            }
            return View(report);
        }

        // GET: Reports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Report report = db.Reports.Find(id);
            db.Reports.Remove(report);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

filipek.pl/Views/Reports/Create.cshtml
@model filipek.pl.Models.Report
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Create";
}
<section class="p-sm-2 header-section text-center">
    <p class="text-center p-3 font-weight-bold">Twój panel</p>
    <p>@Html.Label("Zalogowany jako: ", User.Identity.GetUserName(), htmlAttributes: new { title = "", @class = "nav-link" })</p>
</section>
<nav class="pt-2">
    <ul class="nav nav-tabs">
        @if (Context.User.IsInRole("Admin") | Context.User.IsInRole("Worker"))
        {
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index","Manage")">Moje zgłoszenia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Reports")">Zgłoszenia klientów</a>
            </li>
        }
        @if (Context.User.IsInRole("User"))
        {
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Manage")">Moje zgłoszenia</a>
            </li>
        }
        <li class="nav-item">
            <a class="nav-link active" href="@Url.Action("Create","Reports")">Wystaw zgłoszenie</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("ChangePassword","Manage")">Zmień hasło</a>
        </li>
        <li class="nav-item border-right">
            @Html.Partial("_LoginPartial")
        </li>
    </ul>
</nav>

<section class="py-4">
    @if (ViewBag.Added == "Sukces")
    {
        <h2>Zgłoszenie przekazno do realizacji</h2>
    }
    <div class="card mx-5">
        <div class="card-header bg-primary">
            <h5 class="text-white">Wystaw zgłoszenie</h5>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Reports", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    <label class="col-10">Rodzaj:</label>
                    <div class="col-md-10">
                        <select id="Type" class="form-control" name="Type">
                            <option disabled selected>[Wybierz]</option>
                            <option value="Zamówienie">Zamówienie</option>
                            <option value="Reklamacja">Reklamacja</option>
                            <option value="Zapytanie">Zapytanie</option>
                            <option value="Inne">Inne</option>
                        </select>
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-10">
                    <label>Kategoria:</label>
                    <p>
                        <select id="Category" class="form-control" name="Category">
                            <option disabled selected>[Wybierz]</option>
                            <option value="Pomoc zdalna">Pomoc zdalna</option>
                            <option value="Hosting">Hosting</option>
                            <option value="Serwis PC">Serwis urządzeń peryferyjnych</option>
                            <option value="Odzyskiwanie danych">Odzyskiwanie danych</option>
                            <option value="Serwis telefonów i nawigacji">Serwis telefonów i nawigacji</option>
                            <option value="Uszkodzenia systemu">Uszkodzenia systemu</option>
                        </select>
                    </p>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group col-12">
                    <label>Opis:</label>
                    <p>
                        <textarea name="Description" id="Description" class="col-12 form-control"></textarea>
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </p>
                </div>

                <input type="hidden" name="Status" id="Status" value="Oczekuje" />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Wyślij" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>

</section>
<section class="footer-section">
    <p class="font-weight-bold">Problemy z kontem?</p>
    <p>
        Napisz email do nas na adres: w57003@student.wsiz.rzeszow.pl
    </p>
</section>

filipek.pl/Views/Reports/Delete.cshtml
@model filipek.pl.Models.Report
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Delete";
}

<section class="p-sm-2 header-section text-center">
    <p class="text-center p-3 font-weight-bold">Twój panel</p>
    <p>@Html.Label("Zalogowany jako: ", User.Identity.GetUserName(), htmlAttributes: new { title = "", @class = "nav-link" })</p>
</section>

<section class="py-4">
    <h3>Czy jesteś prewny aby usunąć zgłoszenie o id: @Html.DisplayFor(Model => Model.ID)?</h3>
    <div>
        <hr />
        

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Usuń" class="btn btn-danger" /> 
                <button type="button" onclick="location.href='@Url.Action("Details","Reports", new { id=Model.ID})'" class="btn btn-secondary">Anuluj</button>
            </div>
        }
    </div>
</section>

filipek.pl/Views/Reports/Details.cshtml
@model filipek.pl.Models.Report
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Details";
}
<section class="py-4">
    <div class="card mx-5">
        <div class="card-header bg-primary text-white">
            <span class="ml-5">Zgłoszenie klienta:  @Html.DisplayFor(Model => Model.User)</span>
        </div>
        <div class="card-body mx-5">
            <div class="row">
                <div class="col-md-5">
                    <p>ID zgłoszenia:</p>
                    <p><input type="text" disabled value="@Html.DisplayFor(model => model.ID)" /></p>
                    <p>Kategoria:</p>
                    <p><input type="text" disabled value="@Html.DisplayFor(model => model.Category)" /></p>
                    <p>Rodzaj:</p>
                    <p><input type="text" disabled value="@Html.DisplayFor(model => model.Type)" /></p>
                </div>
                <div class="col-md-4 offset-1">
                    <p class="font-weight-bold">Status:</p>
                    <p>
                        <h4><span id="StatusReport" class="">@Html.DisplayFor(Model => Model.Status)</span></h4>
                    </p>
                    <p class="font-weight-bold">Data utworzenia:</p>
                    <p>@Html.DisplayFor(model => model.Data_of_issue)</p>
                    <p>@Html.DisplayFor(model =>model.User)</p>
                </div>
            </div>
            <p>Opis:</p>
            <p>
                @Html.TextAreaFor(Model => Model.Description, htmlAttributes: new { @class = "col-12 mb-5 form-control", disabled = "disabled", rows = "8" })
            </p>
            @if (Model.Status == "Rozpatrzono" | Model.Status == "Wymaga dodatkowych informacji" | Model.Status == "Odrzucono")
            {
                <p>Odpowiedź pracownika:</p>
                @Html.TextAreaFor(Model => Model.ReplyReport, htmlAttributes: new { @class = "col-12 mb-5 form-control", disabled = "disabled", rows = "8" })
            }
            <p class="text-right">

                @if (Context.User.IsInRole("Admin"))
                {
                    <a href="@Url.Action("Delete", "Reports", new { id=Model.ID})" class="btn btn-danger">Usuń</a>
                }
                @if (Context.User.IsInRole("Admin") | Context.User.IsInRole("Worker"))
                {
                    if (Model.Status == "Oczekuje")
                    {
                        <a href="@Url.Action("Edit", "Reports", new { id=Model.ID})" class="btn btn-warning">Odpowiedz na zgłoszenie</a>
                    }
                }

                @if (Context.User.IsInRole("User"))
                {
                    if (Model.Status == "Oczekuje" | Model.Status == "Wymaga dodatkowych informacji")
                    {
                        <a href="@Url.Action("Edit","Reports", new { id=Model.ID })" class="btn btn-primary">Edytuj</a>
                    }
                }
                @if (Context.User.IsInRole("User"))
                {
                    <a href="@Url.Action("Index","Manage")" class="btn btn-secondary">Powrót</a>
                }
                @if (Context.User.IsInRole("Admin") | Context.User.IsInRole("Worker"))
                {
                    <a href="@Url.Action("Index","Reports")" class="btn btn-secondary">Powrót</a>

                }
            </p>
        </div>
    </div>

    @if (Context.User.IsInRole("Admin") | Context.User.IsInRole("Worker"))
    {
        <div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="replyModalLabel">Odpowiedź na zgłoszenie</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @using (Html.BeginForm("Details", "Reports", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="modal-body">

                            <label>Stan rozpatrzenia</label>
                            <p>
                                <select id="Status" class="form-control" name="Status" required>
                                    <option disabled selected>[Wybierz]</option>
                                    <option value="Rozpatrzono">Rozpatrz pozytywnie</option>
                                    <option value="Wymaga dodatkowych informacji">Rozpatrz neutralnie</option>
                                    <option value="Odrzucono">Rozpatrz negatywnie</option>
                                </select>
                            </p>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <label>Opis:</label>
                            <textarea required name="ReplyReport" id="ReplyReport" rows="12" class="form-control col-12"></textarea>
                            @Html.ValidationMessageFor(Model => Model.ReplyReport, "", new { @class = "text-danger" })
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Wróć</button>
                            <input type="submit" class="btn btn-primary" value="Prześlij" />
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</section>
<script src="~/Scripts/StatusReport.js"></script>

filipek.pl/Views/Reports/Edit.cshtml
@model filipek.pl.Models.Report
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Edit";
}


<section class="py-4">

    @using (Html.BeginForm())
    {
        if (Context.User.IsInRole("User"))
        {
            @Html.AntiForgeryToken()
            <div class="card mx-5">
                <div class="card-header bg-primary">
                    <h5 class="text-white">Edytuj zgłoszenie</h5>
                </div>
                <div class="card-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID)

                        <div class="form-group">
                            <label class="col-10">Rodzaj</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-10">Kategoria</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-10">Opis:</label>
                            <div class="col-md-10">
                                <textarea name="Description" id="Description" rows="8" class="col-12 form-control">@Html.DisplayFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })</textarea>

                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        @*<input type="hidden" name="Status" id="Status" value="Oczekuje" />*@
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="button" onclick="location.href='@Url.Action("Details", "Reports", new { id = Model.ID })'" class="btn btn-danger">Odrzuć</button>
                                <input type="submit" value="Zapisz" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        if (Context.User.IsInRole("Worker") | Context.User.IsInRole("Admin"))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

            <div class="card">
                <div class="card-header bg-secondary">
                    <h5 class="text-white px-4">Odpowiedz na zgłoszenie klienta:</h5>
                </div>
                <div class="card-body form-group px-5">
                    <label>Stan rozpatrzenia:</label>
                    <p>
                        <select id="Status" class="form-control" name="Status" required>
                            <option disabled selected>[Wybierz]</option>
                            <option value="Rozpatrzono">Rozpatrz pozytywnie</option>
                            <option value="Wymaga dodatkowych informacji">Rozpatrz neutralnie</option>
                            <option value="Odrzucono">Rozpatrz negatywnie</option>
                        </select>
                        @Html.ValidationMessageFor(model => Model.Status, "")
                    </p>
                    <label class="col-10">Odpowiedź pracownika:</label>
                    <p>
                        <textarea rows="8" name="ReplyReport" id="ReplyReport" class="col-12 form-control">@Html.DisplayFor(model => model.ReplyReport, new { htmlAttributes = new { @class = "form-control" } })</textarea>
                        @Html.ValidationMessageFor(model => model.ReplyReport, "", new { @class = "text-danger" })
                    </p>
                    <a href="@Url.Action("Details", "Reports", new { id = Model.ID })" class="btn btn-secondary">Wróć</a>
                    <input type="submit" value="Zapisz" class="btn btn-primary" />
                </div>
            </div>
        }
    }

</section>

filipek.pl/Views/Reports/Index.cshtml
@model IEnumerable<filipek.pl.Models.Report>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Index";
}

<section class="p-sm-2 header-section text-center">
    <p class="text-center p-3 font-weight-bold">Twój panel</p>
    <p>@Html.Label("Zalogowany jako: ", User.Identity.GetUserName(), htmlAttributes: new { title = "", @class = "nav-link" })</p>
</section>

<nav class="pt-2">
    <ul class="nav nav-tabs">
        @if (Context.User.IsInRole("Admin") | Context.User.IsInRole("Worker"))
        {
            <li class="nav-item">
                <a class="nav-link " href="@Url.Action("Index","Manage")">Moje zgłoszenia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Index","Reports")">Zgłoszenia klientów</a>
            </li>
        }
        @if (Context.User.IsInRole("User"))
        {
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Manage")">Moje zgłoszenia</a>
            </li>
        }
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("Create","Reports")">Wystaw zgłoszenie</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="@Url.Action("ChangePassword","Manage")">Zmień hasło</a>
        </li>
        <li class="nav-item border-right">
            @Html.Partial("_LoginPartial")
        </li>
    </ul>
</nav>
<section class="py-4">
    <h2>Zgłoszenia klientów</h2>
    <table class="table table-striped my-5 table-hover">
        <thead>
            <tr>
                <th scope="col">Numer</th>
                <th scope="col">Kategoria</th>
                <th scope="col">Rodzaj</th>
                <th scope="col">Data utworzenia</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        @if (Context.User.IsInRole("Admin") | Context.User.IsInRole("Worker"))
        {
            foreach (var item in Model)
            {
                <tbody>
                    <tr class="clickable-row" data-href="@Url.Action("Details", "Reports", new { id=item.ID })">
                        <td>@Html.DisplayFor(modelItem => item.ID)</td>
                        <td>@Html.DisplayFor(modelItem => item.Category)</td>
                        <td>@Html.DisplayFor(modelItem => item.Type)</td>
                        <td>@Html.DisplayFor(modelItem => item.Data_of_issue)</td>
                        <td>@Html.DisplayFor(modelItem => item.Status)</td>
                    </tr>
                </tbody>
            }
        }
    </table>
</section>

<section class="footer-section">
    <p class="font-weight-bold">Problemy z kontem?</p>
    <p>
        Napisz email do nas na adres: w57003@student.wsiz.rzeszow.pl
    </p>
</section>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/StatusReport.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });
</script>